version: "3"
networks:
  nasnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    ipam:
      config:
        - subnet: 10.0.0.0/24
services:
  ctyun:
    image: ghcr.nju.edu.cn/zhuanke8/keepctyun:latest
    container_name: ctyun
    networks: [nasnet]
    restart: always
    volumes:
      - './ctyun:/usr/src/server/data'
